### ISSUE TITLE
npm install update

### ISSUE THREAD

**Issue by nikoewe** [oslabs-beta/react-query-rewind#81]
### Suggestion

This should be updated to `npm i react-query-rewind -D`.
![CleanShot 2024-07-18 at 23 57 46](https://github.com/user-attachments/assets/3c2fa9c2-6581-42c9-8982-e683c2d70195)

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd love to make a PR to improve these docs!

**Comment by johnwdunn20** [comment]
@nikoewe I just double checked and adding the `-D` flag before and after the package name are both valid ways to add a devDependency

**Comment by nikoewe** [comment]
I mean that the package is `react-query-rewind`, not `reactqueryrewind`

**Comment by johnwdunn20** [comment]
I can't believe I missed that - THANK YOU! I just pushed a fix.
